- Observations/eor_firstpass_versions.pro
- fhd_output/calibration_plots/bandpass_plots.pro
Removed an extraneous cgPS_Close that was causing issues on some Linux variants
> Removed an extraneous cgPS_Close 

- fhd_core/visibility_manipulation/vis_header_extract.pro
This contains the snippet you asked me to move to a new PR from the antenna table PR. Please merge this before the antenna table PR and I'll rebase the antenna table branch off this change.
> Add check for multiple spectral windows

- fhd_core/fhd_main.pro
- fhd_core/setup_metadata/fhd_log_settings.pro
- fhd_core/setup_metadata/fhd_save_io.pro
- fhd_core/setup_metadata/fhd_struct_init_layout.pro
- fhd_core/visibility_manipulation/uvfits_read.pro
- fhd_core/visibility_manipulation/vis_header_extract.pro
- simulation/array_simulator.pro
- simulation/array_simulator_init.pro
- simulation/obsolete/fhd_sim.pro
@isullivan please check this carefully, I tried to pass it all the places it needed to go, but I'm not sure I succeeded. I also don't know if you want to use the information from the layout structure anywhere else in your calculations.
This PR addresses issue #45
> Add reading & persisting of uvfits antenna table info

- dictionary.md
- fhd_core/beam_modeling/beam_power.pro
- fhd_core/beam_modeling/beam_setup.pro
- fhd_core/deconvolution/source_detection/components2sources.pro
- fhd_core/gridding/visibility_grid_wrap.pro
- fhd_core/source_modeling/source_array_regrid.pro
- fhd_core/source_modeling/source_dft_multi.pro
- fhd_utils/interpol_2d.pro
We need to finish testing before merging in to master! See Issue #68.
> Beam clipping options

- fhd_core/calibration/vis_calibrate.pro
- fhd_core/calibration/vis_calibrate_subroutine.pro
- fhd_core/fhd_main.pro
- fhd_core/gridding/vis_model_freq_split.pro
- fhd_core/gridding/visibility_degrid.pro
- fhd_core/setup_metadata/fhd_struct_init_meta.pro
- fhd_core/setup_metadata/fhd_struct_init_obs.pro
- fhd_core/visibility_manipulation/transfer_weights_data.pro
- fhd_core/visibility_manipulation/vis_header_extract.pro
- fhd_core/visibility_manipulation/vis_param_extract.pro
> Support Antenna1 and Antenna2 group parameters in uvfits 

- fhd_core/visibility_manipulation/vis_header_extract.pro
> Read frequency as a float from the uvfits header

- fhd_core/calibration/generate_source_cal_list.pro
Very simple fix, which passes the PS jackknife test.
> More general calculation of the pixels in the primary beam

- fhd_core/gridding/visibility_degrid.pro
- fhd_core/gridding/visibility_grid.pro
- fhd_core/setup_metadata/fhd_struct_init_obs.pro
- fhd_core/visibility_manipulation/vis_header_extract.pro
Note that `frequency_array` - derived large arrays are converted back to `float` precision after their derivation.
> Convert frequency_array to double precision

- fhd_core/source_modeling/source_dft_multi.pro
- fhd_utils/FFT/source_dft.pro
These changes resolve issue #164, in which polarized and unpolarized sources were modeling with imaging artifacts in Stokes V.
> Correct source modeling

- dictionary.md
- fhd_core/setup_metadata/fhd_setup.pro
The keyword healpix_recalculate is mentioned in the dictionary but doesn't actually do anything. This pull requests implements a fix to actually recalculate the Healpix cubes when healpix_recalculate is set.
> Use healpix_recalculate keyword

- fhd_core/HEALPix/combine_obs_healpix.pro
- fhd_core/deconvolution/fast_holographic_deconvolution.pro
- fhd_core/deconvolution/fhd_multi.pro
- fhd_output/fft_filters/filter_uv_weighted.pro
- fhd_output/fhd_quickview.pro
- fhd_output/get_image_renormalization.pro
> The weighted FFT filter must recalculate the filter each time

- fhd_core/deconvolution/fast_holographic_deconvolution.pro
- fhd_core/deconvolution/fhd_multi.pro
- fhd_core/fhd_main.pro
This is intended to fix #198. I'm currently re-deconvolving to test this branch.
> Fix deconvolution normalization bug

- fhd_core/beam_modeling/beam_power.pro
> Fix undefined variable bug in beam setup

- fhd_core/calibration/generate_source_cal_list.pro
> fix string formatting

- Observations/general_obs.pro
- dictionary.md
- examples.md
- fhd_core/deconvolution/fast_holographic_deconvolution.pro
- fhd_core/deconvolution/fhd_init.pro
- fhd_core/deconvolution/fhd_multi.pro
- fhd_core/deconvolution/source_detection/components2sources.pro
- fhd_core/deconvolution/source_detection/fhd_source_detect_healpix.pro
Closes #188. We should update the pipeline_scripts repo before merging.
> Replace keyword max_sources with max_deconvolution_components

- fhd_core/polarization/stokes_cnv.pro
> model all 4 source stokes polarizations

- README.md
- dictionary.md
- fhd_core/setup_metadata/fhd_struct_init_obs.pro
- inputs.md
- outputs.md
> Documentation

- dictionary.md
- fhd_core/gridding/dirty_image_generate.pro
- fhd_output/fft_filters/filter_uv_optimal.pro
- fhd_output/get_image_renormalization.pro
> Rename optimal weighting filter

- dictionary.md
- fhd_core/beam_modeling/beam_setup.pro
- fhd_core/calibration/vis_calibrate.pro
- fhd_core/polarization/fhd_struct_init_jones.pro
- outputs.md
- publications.md
Update documentation since it's been awhile.
> Documentation update

- dictionary.md
- fhd_core/calibration/calculate_adaptive_gain.pro
- fhd_core/calibration/fhd_struct_init_cal.pro
- fhd_core/calibration/vis_cal_polyfit.pro
- fhd_core/calibration/vis_calibrate_subroutine.pro
- fhd_core/source_modeling/source_dft_multi.pro
Combining commits from three branches. From @bhazelton: One of them addresses Mike’s issue above (edge_source_fix), one fixes a cable reflection fitting bug (cable_reflection_fix) and one implements Ian’s new calibration speedup (calibration_speedup).
> Cal fix and speedup

- fhd_core/visibility_manipulation/vis_average.pro
Simple update of vis averaging code, defining n_freq and the antenna structures. Solves #176
> Vis avg update

- fhd_core/gridding/visibility_degrid.pro
Fixing the group_arr matrix, now on the degridding side. Similar to #282
> degrid multi-beam fix

- fhd_core/fhd_main.pro
- simulation/in_situ/in_situ_sim_setup.pro
Cleanup of input keywords and spacing of the in situ input. Did a quick run through with a small sim to make sure there was no drastic failures.
> Cleanup of in situ inputs and spacing

- dictionary.md
Just adding a new keyword to the dictionary!
> Add phase_fit_iter keyword to dictionary

- fhd_core/beam_modeling/beam_setup.pro
> Support data with more antennas than baselines

- fhd_core/beam_modeling/beam_setup.pro
> Fix overflow bug in beam setup

- dictionary.md
Just a few updates to the dictionary.
> Djs dict updates

- fhd_core/HEALPix/healpix_bin.pro
- fhd_core/HEALPix/healpix_cnv_generate.pro
- fhd_core/HEALPix/healpix_interpolate.pro
- fhd_core/beam_modeling/fhd_struct_init_antenna.pro
- fhd_core/calibration/generate_source_cal_list.pro
- fhd_core/deconvolution/fhd_multi_wrap.pro
- fhd_core/deconvolution/source_detection/components2sources.pro
- fhd_core/deconvolution/source_detection/fhd_source_detect.pro
- fhd_core/deconvolution/source_detection/fhd_source_detect_healpix.pro
- fhd_core/polarization/fhd_struct_init_jones.pro
- fhd_core/polarization/rotate_jones_matrix.pro
- fhd_core/source_modeling/fhd_galaxy_model.pro
- fhd_core/source_modeling/source_dft_multi.pro
- fhd_core/visibility_manipulation/vis_delay_filter.pro
- fhd_output/fhd_quickview.pro
- fhd_utils/FFT/phase_shift_uv_image.pro
- fhd_utils/format_conversion/globalskymodel_read.pro
- fhd_utils/format_conversion/mrc_catalog_read.pro
- fhd_utils/horizon_mask.pro
- fhd_utils/modified_astro/apply_astrometry.pro
- fhd_utils/modified_astro/pixel_area.pro
- instrument_config/paper_beam_setup_gain.pro
I found a bug in `apply_astrometry` where refraction was applied by default when the intention was to ignore refraction by default. This means that `apply_astrometry` had different default behaviour to AstroPy which ignores refraction by default when doing any conversions unless both temperature and pressure are given. 
It's worth noting the refraction was being applied in world (RA/DEC) to pixel (x, y) and pixel (x, y) to world (RA/DEC) calculations where I doubt the atmosphere comes into play. So with that in mind the code I have done needs a review as these are not breaking changes, but may cause issues.
First thing I have done is changed the double negative of `/ignore_refraction` to a positive keyword `/refraction`. So in order to use refraction you MUST now explicitly use the …
> `apply_astrometry` refraction fix

- simulation/array_simulator_init.pro
- simulation/eor_sim.pro
- simulation/vis_simulate.pro
I have been working with FHD to produce simulations and have come across a few old bugs. Fixing them has allowed me to run `array_simulator` successfully.
> Simulation bug fix
