EoRImaging/FHD

fhd_core/calibration/vis_calibrate.pro, fhd_utils/IDL_tools/pointer_copy.pro
It looks like the extended source information was accidentally being erased during calibration. This happened after model visibilities are created for calibration, so the visibilities should have still been correct. Please check that this branch fixes the problem for you.
=> Bug fix: extended sources were erased from skymodel during calibration

fhd_core/calibration/vis_cal_polyfit.pro, fhd_core/visibility_manipulation/uvfits_read.pro
To get around some permissions issues, I set a readonly flag to the header/uvfits reader. I don't think we'd ever be in a situation where we would like anything other than readonly, but I wanted to check before I pushed to master.
=> /readonly for uvfits read

Observations/eor_firstpass_versions.pro, Observations/eor_wrapper_defaults.pro
`eor_firstpass_versions.pro` has become unwieldy. The intent was to have all commonly used settings in one place so that everyone would use the correct defaults and only change what was needed for their run, but over the years it has grown to the point that rebasing branches is a mess. Instead, I have written a new procedure that contains the general defaults to be used by all standard EOR runs, and individuals or projects can create wrappers that set only the parameters they need, and call  `eor_wrapper_defaults` to set any remaining needed parameters to default values.
=> Wrapper defaults

fhd_core/visibility_manipulation/uvfits_read.pro, fhd_core/visibility_manipulation/vis_param_extract.pro
A recent bug fix copied over the incorrect calculation for default antenna numbering from `baseline_arr`. This pull request implements the correct calculation.
=> Bug fix: antenna numbering from baseline array

fhd_core/HEALPix/healpix_cnv_generate.pro
When converting from image pixels to HEALPix, this first first does a rough calculation of altitude and azimuth, and cuts any pixels with altitude less than 0.
=> Only convert HEALPix indices that are above the horizon

fhd_core/calibration/vis_calibrate_subroutine.pro
Currently, n_vis_cal pulls from the weights pointer, which is purposely not modified by baseline cuts. However, this is false advertising: we want to include baseline cuts in the calculation of n_vis_cal. 
The change I pushed pulls it from a modified versions of the weights. I do this after a for loop over the polarizations, so it will grab the n_vis_cal from the YY pol (instead of the XX pol, which was the default before).
Please comment if you have an opinion.
=> Pull n_vis_cal from modified weights

fhd_core/calibration/vis_calibrate_subroutine.pro
Analog to commit 7ab937e6d62422eeb7c41148d11f00d37084abee that fixed a bug where min_cal_baseline was ignored. This fixes the same bug for max_cal_baseline.
=> ignoring max_cal_baseline bug fix

fhd_core/setup_metadata/fhd_struct_init_layout.pro, fhd_core/visibility_manipulation/uvfits_read.pro
This re-enables creating the layout metadata structure, which was commented out last year by accident. 
It also replaces the new list datatype with older string arrays. This is done both for compatibility with IDL 7, and also because the `keyword_list.count('string')` syntax appears to be system dependent, and raises an error on my machine.
=> Layout bug fix

fhd_output/imagefast.pro
Adds the options `/png` and `/eps` to `ImageFast.pro`. If either is set, FHD will make images in that format, and if neither is set it will make .png by default. Using `/eps` and setting `png=0` will result in only .eps images, and should bypass the requirement to have ImageMagik installed on your machine.
=> Add .png and .eps image output options

fhd_core/calibration/fhd_struct_init_cal.pro, fhd_core/calibration/vis_calibrate_subroutine.pro
If calibration exits because it hits the maximum number of iterations for a given frequency and polarization, it will now print a message to the log, e.g. `Calibration reached max iterations before converging for pol_i: 1 freq_i: 372`
In addition, the number of frequencies that converged is now stored in the `cal` structure and is visible in the settings file. If this does not match the number of frequencies that should have been used, you can investigate further by looking through the `cal.convergence` parameter.
=> Add output message and settings file entry for cal convergence

fhd_core/polarization/fhd_struct_init_jones.pro, fhd_core/setup_metadata/fhd_struct_update_obs.pro
This pull request resolves issue #153, where imaging was failing when max_baseline was small.
Imaging failed because the Jones matrix was infinite. This came from line 69 in fhd_struct_init_jones.pro, where power_zenith was being set to 0. In line 70, the Jones matrix is divided by power_zenith, leading to infinite values and NANs for the visibilities. In line 69 power_zenith_beam has a resolution of 2048 and obs_temp.zenx and obs_temp.zeny were each ~128. After the fix obs_temp.zenx and obs_temp.zeny are ~1024 and the interpolation in line 69 gives a non-zero value.
=> bug fix: beam resolution mismatch

fhd_core/polarization/fhd_struct_init_jones.pro, fhd_core/polarization/stokes_cnv.pro, instrument_config/mwa_beam_setup_gain.pro
This pull request changes the Jones matrix to double precision, from float. It also includes a bug fix for the Stokes conversion.
These changes were motivated by work done on the Stokes_basis_coordinates branch. We found that Stokes I source modeling depended on the coordinate system. This dependency was due to machine precision errors and disappeared when we began using a double precision Jones matrix. 
Here is a power spectrum difference plot of master minus double_precision_beam:
=> Make the Jones matrix double precision and correct a Stokes conversion bug

fhd_core/visibility_manipulation/vis_header_extract.pro
The crash using the new uvfits headers with LST added was because the number of parameters increased from 9 to 11. The header interpreter formatted the "PTYPE" keywords with only a single integer, so parameters past 9 could not be read. This removes that limitation.
=> Bug fix: uvfits headers can have 10+ parameters

fhd_core/polarization/fhd_struct_init_jones.pro
This change treats the Jones matrix as complex. The change has no impact on the XX or YY images (and therefore does not impact the power spectra). It has a small affect on the Stokes images.
=> Complex Jones matrix

fhd_core/gridding/dirty_image_generate.pro, fhd_core/gridding/vis_split_export_multi.pro, fhd_core/polarization/crosspol_reformat.pro, fhd_core/polarization/stokes_cnv.pro, fhd_output/crosspol_split_real_imaginary.pro, fhd_output/fhd_quickview.pro
These changes resolve a bug that made the Stokes V images identically zero. Previously, the XY and YX maps were constrained to be real, which forced Stokes V to be zero. These changes allow for complex XY and YX maps and resolve an error gridding those maps. They affect the Stokes images only. The branch has been tested and it has no impact on the power spectrum.
=> Stokes V calculation fix

fhd_core/polarization/stokes_cnv.pro
This is a small change that just gives a slightly more informative error message in stokes_cnv when all sources in the catalog are below the horizon.
=> Add error handling for when no sources found

fhd_core/deconvolution/fast_holographic_deconvolution.pro, fhd_core/deconvolution/source_detection/process_deconvolution_components.pro, fhd_core/deconvolution/source_detection/source_comp_init.pro
This collects a few modifications to the source and component lists at the end of deconvolution and moves those to a new function. I then also add a new tag to those structures to contain the beam value at the location of the source or component, and include that calculation in the new function. So far, this is only calculated at the end of deconvolution, though it could be added for the source arrays used in calibration.
Old code should safely ignore the new information in the source array.
=> Add beam to source list

fhd_core/calibration/generate_source_cal_list.pro, fhd_core/deconvolution/source_detection/source_comp_init.pro, fhd_core/setup_metadata/load_source_catalog.pro
This fixes a bug where an old source structure restored from a .sav file has incompatible tags with the current definition of the structure. It generates a new source structure, and fills each tag of the structure with values present in the loaded structure. The same treatment is applied to any extended sources. Any missing values are left at their defaults (as defined in `source_comp_init.pro`), and any extraneous tags are discarded. Warning messages in either case are printed to the log.
=> Fix source structure bug

fhd_core/polarization/fhd_struct_init_jones.pro
Jones matrix reverted to real when restored, causing issues with the Stokes conversion
=> complex Jones bug

fhd_core/calibration/vis_calibrate.pro, fhd_output/fhd_quickview.pro
The keyword `no_png=1` will now also be passed in to calibration, and will also turn off making .png plots of the calibration solutions.
=> Add option to turn off plotting calibration solutions

fhd_core/beam_modeling/beam_power.pro
Fix to calculate the power beam from the Jones matrix correctly. This change has a small impact on the power spectrum. 
Here is the difference power spectrum from Aug 23, 2013, master minus branch:
And here is the power spectrum ratio:
This change affects the beam at a level of ~10^-5. Here is the beam from master minus the beam from the branch for a zenith pointing:
and for a non-zenith pointing:
Note that these beams are peak-normalized to 1.
=> Rework the power beam calculation

fhd_core/source_modeling/fhd_struct_init_skymodel.pro
I've tested this branch and it successfully resolves a bug. The bug prevented modeling diffuse emission without also using a point source catalog for modeling, even if the point sources were previously modeled during calibration.
=> Allow source modeling to be explicitly turned off

fhd_output/get_image_renormalization.pro
Using a single normalization across polarizations caused catastrophic errors in imaging when "optimal weighting" (FFT filter "fiter_uv_weighted") is used. PR #181 implemented per-pol image normalization for that weighting scheme only. This PR implements per-pol normalization for all weighting schemes, not just optimal.
=> Use per-pol image normalization for all image filters

fhd_core/beam_modeling/beam_image.pro, fhd_core/beam_modeling/beam_power.pro
The transformations of the beam between the sky and UV frames use the opposite FFT conventions of the transformations of the data and images. This has the result of flipping the UV-space beam in both dimensions, which gives the correct sign convention when gridding visibilities. If the beam were not flipped in UV space then the apparent sky images would be weighted by the flipped beam, not the true beam. This sign convention was obfuscated in the code. Also, the call to `dirty_image_generate` in `beam_power` was confusing to me. This PR is an attempt to make things somewhat more explicit (although eventually we should probably have a memo explaining all this).
=> Document the flipped orientation of the beam in UV space

dictionary.md, fhd_core/calibration/generate_source_cal_list.pro, fhd_core/deconvolution/source_detection/source_comp_init.pro, fhd_core/fhd_main.pro, fhd_core/gridding/visibility_grid.pro, fhd_core/setup_metadata/fhd_setup.pro, fhd_core/setup_metadata/load_source_catalog.pro, fhd_core/source_modeling/source_dft_multi.pro, fhd_output/fhd_quickview.pro, fhd_utils/FFT/source_dft.pro, fhd_utils/run_report.pro
Allows model catalogs to include Gaussian shape information for sources or source components. These changes do not affect runs unless the keyword gaussian_source_models is set.
=> Gaussian source modeling

fhd_core/setup_metadata/fhd_setup.pro, fhd_core/setup_metadata/fhd_struct_update_obs.pro
1) The beam recalculate option I put in previously did not always get used because of a resetting of the status string that I hadn't noticed. I moved the logic earlier so that it takes precedence. Tested, works.
2) During the making of healpix cubes, the obs structure is updated and stored with the cubes. The frequency array is recast to floats during the process. I removed the recast so that the frequencies are as accurate as possible (important for eppsilon frequency dft-ing). Tested, works.
=> simple hotfixes

fhd_core/beam_modeling/fhd_struct_init_psf.pro
This is a simple 1-line fix that just makes the defaulting in `fhd_struct_init_psf.pro` match `fhd_struct_init_antenna.pro`. See #192
=> Change psf_resolution behavior to comply with intended default

fhd_core/calibration/vis_calibrate.pro, fhd_core/calibration/vis_calibration_flag.pro
NaN's weren't being correctly handled during calibration flagging (particularly in calculating standard deviations). This doesn't actually affect the calibration solutions and calibrated visibilities (applying a NaN calibration effectively flags that visibility anyways) but it *does* affect the metadata and associated counting statistics.
In addition, zeroed or NaN'd calibration solutions were not being translated into flagged tiles/frequencies when calibration solutions were transferred. I've found where the flagged frequencies and tiles were in the calibration solutions, and then broadcasted them across pols. Is that the general behaviour that we want?
=> Correctly handle nans in cal flagging and transfer flags

fhd_core/beam_modeling/beam_power.pro, fhd_core/beam_modeling/fhd_struct_init_antenna.pro, fhd_core/beam_modeling/general_antenna_response.pro, fhd_core/deconvolution/source_detection/source_comp_init.pro, fhd_core/polarization/fhd_struct_init_jones.pro, fhd_core/polarization/rotate_jones_matrix.pro, fhd_core/source_modeling/source_dft_multi.pro, fhd_utils/FFT/source_dft.pro, instrument_config/hera_beam_setup_gain.pro, instrument_config/mwa_beam_setup_gain.pro, instrument_config/paper_beam_setup_gain.pro
To reduce memory load, only store values of the zero-padded beam image which are not zero. Subsequently, store their array index so that zero-padded beam images can be made on the fly during degridding/gridding.
This reduces the memory load significantly, up to 50% when 384 freq-dependent beams are used.
One additional commit: force the gaussian source models to use the true dft versus the dft approximation. @isullivan, can you confirm whether or not the gaussian source models can use the dft approximation? The gaussian source models are made be multiplying a point source uv-plane with a gaussian envelope, a la [Line et al. 2020](https://arxiv.org/abs/2005.09316) Eq 11.
=> Reduce mem

fhd_core/fhd_main.pro, fhd_core/setup_metadata/fhd_setup.pro
The beam recalculation logic is too fragile, and needs to be extracted from the main branch for now.
Some recent requests have indicated that a rethink of some other recalculation keywords would be handy, so we should pick this back up in another branch in the future.
=> Fragile beam recalculation keyword needs to go

fhd_core/gridding/split_vis_weights.pro
When the weights were split into even/odd time samples, the time cutting was not being handled properly when there was more than one cut time.
=> Flag weights for cut times during split

fhd_core/visibility_manipulation/vis_flag_basic.pro
Skip flagging the coarse channel edges rather than throwing an error if `channel_edge_flag_width=0` on the command line.
=> Allow MWA coarse channel flagging to omit coarse channel edges

fhd_core/calibration/vis_cal_polyfit.pro, fhd_core/calibration/vis_calibrate_subroutine.pro
Due to a bug, setting `cal_mode_fit` to an array of multiple cable lengths caused an error. This PR fixes that bug.
It also improves the printed message when a freq, pol doesn't converge in calibration to include the amount the convergence was off by and the convergence tolerance so the user can tell how off they were.
=> Fix a bug preventing fitting reflections on multiple cables, improve convergence print statement

fhd_core/HEALPix/healpix_snapshot_cube_generate.pro, fhd_core/gridding/vis_model_freq_split.pro
Fairly straightforward speed-up of Healpix export code. There was an unnecessary middle-man pointer when reorganizing the Healpix cubes into vectors. Since the Healpix cubes are so large, removing this excess reduced the runtime by about 6 minutes and reduced memory needed by a few Gb. A slight reordering of a `for` loop was also done in the even/odd split, but this probably is a minuscule effect. 
There is no change in the power spectra
=> Speed up Healpix export code 

fhd_core/gridding/visibility_degrid.pro, fhd_core/gridding/visibility_grid.pro
1. Gridding and degridding close to the v=0 line.
Before, whenever a baseline uv-footprint touched the v=0 line, it was flagged. However, I think this is unnecessary. As long as the *center* of the baseline is above v=0, it can be included. This does mean that the footprint will extend into negative v range. In practice, we only grid half of the uv plane and then flip/conjugate and add the two together, which is why I think there was hesitation to include baselines which span both sides of the v=0 line.
I had a good long think about this effect earlier, when I was attempting to do semi-analytic gridding. In that case, a baseline would contribute to *all* of the uv-plane. As long as you grid the top half, but record how that half bleeds downs into the bottom half, the math checks out when …
=> Three rare or minor gridding effects

fhd_core/calibration/initialize_fhd_struct.pro, fhd_core/calibration/vis_calibrate.pro
This simple function creates a placeholder structure of the specified type, and deletes it. This defines the structure parameters for the current IDL session and ensures consistency when restoring structures of that type.
=> Add simple function to define named structures

fhd_core/gridding/visibility_degrid.pro, fhd_core/gridding/visibility_grid.pro
I've made some slight modifications to gridding and degridding for a modest speed-up of about 10 minutes total on a typical run. 
Changes include:
- Reducing `interp` IF statements by grouping them together. I only have had to do a small amount of code redundancy to make this happen
- Removing internal time calls. Apparently this was a time sink
- Removing the FLOOR call in an index calculation. It was unnecessary as far as I can tell.
- General aesthetic cleanup
Running on this branch and the master branch produced the same exact power spectra (tested with the `interp` keyword)
=> Rearrange (de)grid and remove excess time calls for speed up

fhd_core/gridding/visibility_degrid.pro
In the degridding procedure, we degrid *all* visibilities. This includes the autos, which imposes a slight memory problem.
Problem: We degrid by region, choosing a square in uv-space and selecting all visibilities which fully fall within this square and degrid them. Then, we move the square and repeat, covering the full uv-space. When we pass over the u=0,v=0 point, we suddenly have *all* the autos to degrid at once. This results in a memory spike up to roughly 50Gb for that loop.
Solution: Add an option which splits up the degridding process into sub-loops if it surpasses an estimated memory usage. There already exists something similar for source dfts (`conserve_memory`) so I've co-opted that keyword. 
Here is the memory usage for a run with this sublooping. Solid yellow is memory …
=> Enable optional memory loops in degridding

fhd_core/setup_metadata/fhd_struct_init_meta.pro
Instead of throwing an error after calibration/modelling, throw an error as soon as it's apparent that the metadata has flagged all of the tiles. 
(In the MWA, metadata flags all of the tiles if it did not get reporting stats from the receiver, thus being unable to determine the quality of the array during the obs).
=> Check if metadata flags all tiles

fhd_core/beam_modeling/beam_setup.pro
Small error that I just implemented with the documentation code. I added an `undefine` to try to clear up the unneeded structure, but it frees the pointers which are used in the true `psf` structure. I've removed that `undefine` since it's not really needed since that parameter won't be passed on anyways.
=> Undefined pointer hot fix

fhd_core/beam_modeling/general_antenna_response.pro
Implementing strategies used in the past to the general antenna response.
Instead of calculating the general antenna response at every location in the full zero-padded beam image, only calculate it at pixel locations within the horizon (i.e. where it is non-zero). This is a drastic improvement in memory (reducing from 70Gb required to 20Gb on my current test, reduction will be dependent on beam resolution and zero-padding) and a good improvement in time (no reforming required, and no calculating 0 many many times, reduction by a few minutes).
=> Further memory reduction

fhd_core/calibration/vis_calibrate_subroutine.pro
Preemptively set gains which do not satisfy the minimum number of equations set forth in the linear least squares solver to 0. This removes them from the strict convergence threshold, solving issue #258. Otherwise, that frequency generally fails the strict convergence rather quickly. 
It should be noted that this biases the loose convergence threshold (a mean of the tiles for the frequency). However, this was present before as well for other zeroed cases.
=> Remove gains which don't satisfy conditions from strict convergence

fhd_core/calibration/generate_source_cal_list.pro
If nan fluxes are present, then warn the user and remove them from source modelling.
=> Nan flux hotfix

fhd_core/gridding/visibility_grid.pro
In a rarely used option, there was a bug in where the box matrix was being initialized. The value of vis_n changes in this rarely used option, so the box matrix should be initialized right before it is used instead of outside the loop.
I then got carried away and started putting in comments in the gridding function. Help would most definitely be appreciated!
=> Fix box matrix bug and add gridding comments

fhd_core/calibration/generate_source_cal_list.pro
Accidentally left off the update of the number of sources used if nan fluxes were removed.
=> also update the num of sources used

fhd_core/gridding/baseline_grid_locations.pro, fhd_core/gridding/visibility_count.pro, fhd_core/gridding/visibility_degrid.pro, fhd_core/gridding/visibility_grid.pro, fhd_output/fft_filters/filter_uv_optimal.pro, fhd_output/fft_filters/filter_uv_uniform.pro
There was a lot of redundant code between `visibility_grid`,`visibility_degrid`, and `vis_count`. I've condensed the majority of the redundant code to a new file, `baseline_grid_locations`. This file returns information regarding the locations of the unflagged visibilities in units of pixels in a variety of different forms.
Each of the three original files accounted for flagging in a slightly different way, and I've recreated each of those. The only exception being that unsetting `fill_model_visibilities` during the model making process will emulate the flagging done for gridding with this new file -- arguably what we want to do anyways. In any case, `fill_model_visibilities` is currently hard set on anyways. 
The power spectra for a typical run are the same between the old branch and the …
=> Redundant code to a single file

fhd_core/calibration/fhd_struct_init_cal.pro, fhd_core/calibration/vis_calibrate.pro, fhd_core/deconvolution/fast_holographic_deconvolution.pro, fhd_core/fhd_main.pro, fhd_core/source_modeling/vis_model_transfer.pro, fhd_core/source_modeling/vis_source_model.pro
Extra instances to transfer 1) model visibilities and 2) a simulated model uv-plane without the instrument. This allows for the code to input model visibilities in a more efficient manner (i.e. in a separate transfer module), or to input a theoretical model uv-plane with only source contributions. The latter is helpful for simulations/parameter changes, and the former is helpful for double data runs (separate kernel for cal and gridding).
=> Model transfers

fhd_output/fft_filters/filter_uv_robust.pro, fhd_output/fhd_quickview.pro
This is an implementation of robust/Briggs weighting for images, where `robust_param` is used to encode the robust scaling. It ranges from -2 to 2, where -2 is close to uniform weighting and 2 is close to natural weighting. Below are simulations of point sources in dirty Stokes I for robust weightings of -2, -1, 0, 1, and 2 (no noise).
Here is a locked DS9 tiled image:
And again, oversaturated
And a gif of the automatically made FHD images
The extreme ends look correct (-2 ~ uniform, 2 ~ natural), but I have no frame of reference for in-between values. It would be great if someone experienced in what robust weighting looks like could advise if this is the normal behaviour.
=> Adding robust filter

fhd_core/gridding/visibility_grid.pro
As mentioned in Slack:
> I think Joel may have found a bug, and I wanted to get your opinion.
> Line 64 of visibility_grid.pro finds the group identifier if there are multiple beams being used:
> group_arr=reform(psf.id[polarization,freq_bin_i[fi_use],bi_use])
> However, bi_use has the same dimensionality as the num of visiblities (4 million something), and psf.id has the dimensionality of x, x, 8128 . It doesn’t error, but I think the group_arr is set to the last value in the array if it exceeds 8128.
> I think maybe bi_use should be bi_use_reduced. I wanted to check with you though, because it seemed like this could have potential for IDL black magic.
> Maybe this hasn’t been an issue thus far because we generally use one beam. And maybe this explains why our dead dipole tests never …
=> group_arr psf.id bug

fhd_core/beam_modeling/gaussian_decomp.pro
I thought I had fixed this, but apparently I hadn't. 
It's a splitting of the array into chunks if a lower memory footprint is required. Tested and works now. Only affects the Gaussian decomposition.
=> Mem splitting bug fix

fhd_core/beam_modeling/beam_setup.pro, fhd_core/gridding/visibility_grid.pro
There were a few lingering bugs regarding the ID group array, which determines which baselines have the same beams. This is a rarely used option (at this stage).
This has been tested to give the proper IDs on two separate tests. There may remain some edge cases that I wasn't able to think of, but this should cover most cases with this option.
A warning was also added from the suggestion of Joel.
=> Multi-beam fixes

fhd_core/visibility_manipulation/vis_extract_autocorr.pro
This fixes a bug in which FHD fails when an observation has only one time step.
=> Support observations with one time

fhd_core/source_modeling/source_dft_multi.pro, fhd_utils/FFT/fast_dft_subroutine.pro, fhd_utils/FFT/source_dft.pro
I updated the gaussian source model generation. There are a couple of changes:
1) better gaussian parameter passing. I created a new structure so things are now much more compact and easier to manage.
2) including image plane -> uvw compression math from Jaiden's upcoming paper. Instead of calculating the mean compression from output from `apply_astrometry`, I'm calculating the expected compression using geometry. I've attached a screenshot of the relevant math. 
3) switching the `source_dft` matrix ordering so that it's column major to be faster in IDL. This was a simple fix that significantly decreased walltime and mem requirements.
4) small bugs and general spacing. 
The main branch (with Christene's LoBES catalog) took 381 min at 94 Gb for 69 118 sources. The new branch took 326 min …
=> Gaussian model update

dictionary.md, fhd_core/HEALPix/healpix_interpolate.pro, fhd_core/source_modeling/fhd_diffuse_model.pro, fhd_core/source_modeling/vis_source_model.pro
In order to reduce aliasing when FFTing the diffuse map, I've added options for anti-aliasing windows before and after the FFT. I also found a small error with reading in Kelvin maps, which I think made it really difficult to compare Jy/str maps with Kelvin maps.
----Bug fix
When calculating the pixel area, the nside of the Healpix map was used instead of the pixel size of the flat, output map. Since the calculation is used to generate an output Jy/pixel map, the pixel area needs to be the output size. This doesn't affect Jy/str maps. This was in `healpix_interpolate.pro` which doesn't seem to be used anywhere else, so I think it's safe to change it there.
----Diffuse options
This gives the user the option to play with a variety of different spectral windows. However, I've found the …
=> Diffuse options

fhd_core/fhd_main.pro, fhd_core/setup_metadata/fhd_struct_init_meta.pro, fhd_core/setup_metadata/fhd_struct_init_obs.pro, fhd_core/visibility_manipulation/uvfits_read.pro
Quick little fix for the pyuvdata antenna naming convention. I admit that it may not be the best fix....
For starters, there is an assumption that the number of tiles would be less than antenna names, and that the antenna names are numbers. These are both assumptions that could break. 
fixes #292
=> antenna indices rewrite

fhd_core/setup_metadata/fhd_struct_init_obs.pro, fhd_core/visibility_manipulation/vis_header_extract.pro, fhd_core/visibility_manipulation/vis_param_extract.pro
Some uvfits files were resulting in the following error during gridding/degridding:
`% Unable to dereference NULL pointer: <POINTER  (<NullPointer>)>.`
This was tracked down to two different bugs. In one case, the code which maps antenna numbers to indices was not being triggered. In another case, only using one of the two uvfits date fields resulted in an incorrect calculation of the number of baselines.
Both of these bugs are fixed here. Additionally, I have added a check which makes sure that all the elements from the uvfits header antenna arrays are present in the antenna numbers array from the antenna table.
=> Fix bugs causing errors while gridding/degridding

fhd_core/beam_modeling/beam_setup.pro
Minor update to allow `transfer_psf` keyword to work when the `beams` and `obs` structures are in different directories (as is true for the default output format). Previously, the if statement on line 24 would pass when `transfer_psf` was a directory, and then fail in `getvar_savefile` when trying to restore the directory - this change means that this if statement is skipped if the keyword is a directory rather than a file, and is instead handled in the following chunk of code.
=> Make transfer_psf work when beams and obs are in different directories

instrument_config/mwa_beam_setup_gain.pro
Changing the default option on the interpolation on the beam in frequency from linear to quadratic to remove the coarse band lines in simulation.
=> quadratic interpolation of the beam in freq

fhd_core/fhd_main.pro
Add functionality to save metadata and, optionally, visibility files when cal_stop is called.
=> Save vis and metadata files when cal_stop is called

fhd_core/visibility_manipulation/vis_baseline_hist.pro
This fixes an indexing issue found by Jack (@JLBLine) during the PyFHD testing, this should fix the results and save the values in each polarization rather than overwriting each polarization per loop inside the `vis_res_ratio_mean` and `vis_res_sigma` arrays. PyFHD and FHD get *almost* (precision error) the same results with this fix applied.
The previous `vis_baseline_hist`:
The fixed `vis_baseline_hist`:
=> Fix indexing for `vis_baseline_hist`

dictionary.md
Documentation in the dictionary listed incorrect default units for `diffuse_model`.
=> Correct diffuse_model documentation

fhd_core/gridding/vis_model_freq_split.pro, outputs.md
Also separate pols into different files and save uvf cubes in the `grid_data` subfolder.
Going to 3D complex arrays rather than pointers and separating the pols into different files speed up eppsilon significantly.
The new location for the cubes keeps the folder structure clean but does require some minor updates on eppsilon.
=> make uvf cube outputs be 3D arrays rather than pointer arrays

fhd_core/deconvolution/source_detection/group_source_components.pro
If `sub_expand` is less than one, then the code errors. Instead, print a warning message and manually set `sub_expand=1`.
=> Create check on sub_expand

dictionary.md, fhd_core/fhd_main.pro, fhd_core/setup_metadata/fhd_save_io.pro, fhd_core/source_modeling/fhd_struct_combine_skymodel.pro, fhd_core/source_modeling/fhd_struct_init_skymodel.pro, fhd_core/source_modeling/source_list_append.pro
Some skymodel behaviour was very opaque, as pointed out by Shijiao. So, I set out to make it a little more obvious what is going on.
**Previous functionality**
When `return_cal_visibilities` is set, then the calibration visibilities are kept around after calibration. If a different set of visibilities need to be calculated for the subtraction model, only sources that are *extra* to the initial calibration sources list are calculated and added to the returned calibration visibilities. This assumes that the calibration sources are a subset of the model sources. While this reduces the number of calculations, it is not obvious from the user that setting `return_cal_visiblities` would cause this behaviour.
The skymodel that is saved, regardless of whether or not `return_cal_visibilities` is …
=> Reducing skymodel confusion

fhd_core/calibration/fhd_struct_init_cal.pro, fhd_core/calibration/vis_cal_bandpass.pro, fhd_core/calibration/vis_calibrate.pro, fhd_core/source_modeling/vis_model_transfer.pro, fhd_core/source_modeling/vis_source_model.pro, fhd_output/calibration_plots/plot_cals.pro, fhd_output/calibration_plots/plot_cals_sub.pro
These are miscellaneous calibration changes:
1) Store the used bandpass in the cal structure. This is important if you want to reconstruct each step of calibration after a run has finished. Purely for metadata/storing/tracking purposes.
2) Remove NANs from the yrange calculation of calibration plots for better viewing. This is something that rarely happens, but if you are playing around with some simulations and doing some hand-flagging, it's possible.
3) Model transfer framework that can handle WODEN inputs. Some time/baseline matching needs to occur because WODEN makes the full-model without flagging. This is kept very generalized to work with previous versions of WODEN that had a JD offset (noon versus midnight). 
All changes have been confirmed to work in PS.
=> Calibration misc

fhd_core/setup_metadata/fhd_struct_init_meta.pro, fhd_core/setup_metadata/fhd_struct_init_obs.pro
This one is bit complicated. This is in response to issue #311 .
The suggested fix in #311 could be more generalized. For example, the metadata file is actually structured such that the Y pol is before the X pol (why?!?!). Even though we currently flag XX, YY, XY, and YX the same *currently* doesn't mean we always will want that. Therefore, I've constructed a way that is generalized.
Essentially, the code grabs the individual dipole flags and matches their metadata name (i.e. X) to a component in the cross-correlation name (i.e. XY). Then a logical OR is performed to get the cross-correlation flag. 
So, an X-dipole flag will end up flagging XX, XY, and YX. But not YY.
No difference in the 2-pol. Only difference is in 4-pol flagging.
This will need to be implemented in pyFHD (low-priority) …
=> convert tile flag to cross-corr flags

fhd_core/setup_metadata/fhd_struct_init_obs.pro, fhd_core/visibility_manipulation/vis_flag_basic.pro
This fix addresses issue #321, where the auto calibration was using times which should have been flagged.
This underlying root cause is that the time_use array was not checked against the weights array. In the case of SSINS, the weights for an entire time step will flagged, but this was not propagating to the time_use array in FHD. The time_use array is used a few circumstances, the two major instances being 1) auto calibration averaging and 2) noise calculation. Given that this affects the results in a few places, there is an overall change in the PS.
Below is a test against a control for an observation that had 4 SSINS flagged times. Differences are small and somewhat hard to interpret. Not sure if we want to pursue this differences deeper or if we are happy to take the fact that this …
=> Proper tracking of flagged times
